# Generated by Django 3.1.5 on 2021-01-16 16:43

from django.db import migrations, models
import django.db.models.deletion

from orders.models import VehicleType, Slot, DeliveryVehicle


def populate_initial_vehicles(*args):
    """Populates the initial vehicle types available
    """
    VehicleType.objects.create(name='bike', vehicle_capacity=30)
    VehicleType.objects.create(name='scooter', vehicle_capacity=50)
    VehicleType.objects.create(name='truck', vehicle_capacity=100)


def populate_initial_slots(*args):
    """Populates the initial slots available
    """
    slot_1 = Slot.objects.create(slot_number=1)
    slot_1.vehicle_types_assigned.set(VehicleType.objects.filter(id__in=[1, 2]))

    slot_2 = Slot.objects.create(slot_number=2)
    slot_2.vehicle_types_assigned.set(VehicleType.objects.filter(id__in=[1, 2, 3]))

    slot_3 = Slot.objects.create(slot_number=3)
    slot_3.vehicle_types_assigned.set(VehicleType.objects.filter(id__in=[1, 2, 3]))

    slot_4 = Slot.objects.create(slot_number=4)
    slot_4.vehicle_types_assigned.set(VehicleType.objects.filter(id__in=[3]))


def populate_initial_delivery_vehicles(*args):
    """Populates the initial delivery vehicles available
    """
    num_bikes = 3
    num_scooters = 2
    num_trucks = 1

    bike = VehicleType.objects.get(name='bike')
    for i in range(1, num_bikes+1):
        DeliveryVehicle.objects.create(vehicle_type=bike, delivery_vendor_id=i)
    scooter = VehicleType.objects.get(name='scooter')
    for i in range(1, num_scooters+1):
        DeliveryVehicle.objects.create(vehicle_type=scooter, delivery_vendor_id=i)
    truck = VehicleType.objects.get(name='truck')
    for i in range(1, num_trucks+1):
        DeliveryVehicle.objects.create(vehicle_type=truck, delivery_vendor_id=i)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('delivery_vendor_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicleOrders',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('delivery_vehicle', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('slot_number', models.PositiveSmallIntegerField(choices=[
                 (1, '6-9'), (2, '9-13'), (3, '16-19'), (4, '19-23')], default=None)),
                ('slot_start_time', models.TimeField(null=True)),
                ('slot_end_time', models.TimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('vehicle_capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlotDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('vehicles_assigned', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.slot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='vehicle_types_assigned',
            field=models.ManyToManyField(to='orders.VehicleType'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('delivery_vehicle_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                             related_name='orders', to='orders.deliveryvehicleorders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deliveryvehicleorders',
            name='slot_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='delivery_vehicle_orders', to='orders.slotdelivery'),
        ),
        migrations.AddField(
            model_name='deliveryvehicle',
            name='vehicle_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='orders.vehicletype'),
        ),
        migrations.RunPython(populate_initial_vehicles),
        migrations.RunPython(populate_initial_slots),
        migrations.RunPython(populate_initial_delivery_vehicles),
    ]
